### ISSUE TITLE
Add Arduino MIB that better supports home automation

### ISSUE THREAD

**Issue by mikaelpatel** [mikaelpatel/Cosa#110]
The current Arduino MIB example allows access to digital and analog pins, and power supply voltage read. There is a need to show how SNMP can also be used for read of OWI (DS18B20), TWI(RTC/BMP) and maybe even memory (SRAM/EEPROM). 

A sub MIB structure for 1-wire is especially interesting. 

arduino/1-wire/dev/0/rom/BYTE[8], alarm/BOOL, attribute3..n (family dependent)

For DS18B20 sub-mib with /temperature, /resolution /threshold

**Comment by dansut** [comment]
This area is especially interesting to the project I am working on which will require just this sort of functionality - presently am working with DHT but in the long run sensors that are addressed serially will make more sense for expansibility. I'm willing to put my time into expanding Cosa in this area of SNMP wherever I can be useful.

**Comment by mikaelpatel** [comment]
Thanks for offering help with this part of Cosa. As you might have seen this has been "out of focus" for some time. I will try to pull out the old design sketches on this. A lot has with allowing configuration of sensors such as the DS18B20 and common interconnects (SPI, TWI, OWI, etc). 

This work also has to do with creating a naming structure in MQTT. It is very much a MIB as well. 

Cheers! Mikael

**Comment by dansut** [comment]
MQTT is also very much on my radar as a protocol that could be very useful in my project - I was originally drawn to SNMP having worked with it many years ago and seeing as a quick way to get my prototype working...

I am fairly new to the Arduino prototyping world but have many years in the computer industry and am enjoying the challenges it is providing - I fairly quickly found limitations in the stock Arduino libraries and research led me to Cosa which feels much more the way I think and code.

Although C++ OOP is a bit of a dusty old memory for me, it is a fond one, and many things are starting to come flooding back. I may need a bit of mentoring along the way, if you don't mind, but I think I can prove myself very helpful for Cosa as I see it being extremely useful for my project. It is a commercial project but we are more than happy to get involved in open source and give back more than we are obliged to.

Cheers
/dan

**Comment by mikaelpatel** [comment]
To be moved to Domotica. https://github.com/mikaelpatel/Cosa-Domotica
