### ISSUE TITLE
Versioning vs. Continuous Changes 

### ISSUE THREAD

**Issue by rei-vilo** [mikaelpatel/Cosa#224]
Cosa is a great project but it doesn't feature versioning.

With continuous changes, Cosa is difficult to work with, as there's no version number. So no one knows which version one's using.

I suggest releasing versions, for example on a quarterly basis.

Thanks!

**Comment by rei-vilo** [comment]
The links to the versioned `.zip` files seem to have disappeared from the [Install documentation](https://github.com/mikaelpatel/Cosa/blob/master/doc/02-install.md#download-versions). This puts the embedXcode support for Cosa in jeopardy. 

Are you aware GitHub includes a built-in [release mechanism](https://github.com/mikaelpatel/Cosa/releases)? Why not to use it? Check the [Creating Releases](https://help.github.com/articles/creating-releases/) tutorial.

**Comment by mikaelpatel** [comment]
Yes the zip files have been removed from the installation section. I think that the simplest solution is to just take the latest version as zipped by github. There is so little reporting on my end so that the extra work for a release is just a waste of time. Are you receiving reports on your end?

**Comment by rei-vilo** [comment]
Going through [Creating Releases](https://help.github.com/articles/creating-releases/) tutorial only requires a couple of seconds, especially once a trimester. Versioning is key when distributing software. 

Yes, when a user has a problem with Cosa, the first question is always when he/she downloaded the framework. Very time consuming and useless.

**Comment by mikaelpatel** [comment]
@rei-vilo 
Thanks for your swift response. As I mentioned I have not had any issue reports of this nature and found it unmotivated to do releases (with or without the github release handling). 

There is a big difference between embedXcode and Cosa. I am simply sharing my work, unversion, unsupported, etc. I do not have time or resources to support users that download from github and most seem to understand this. 

Are you receiving many issue reports regarding installing Cosa? There has been a fair number of changes to the Arduino AVR tool chain (1.6.3) that might give problems but so far there are no issue reports on Cosa. What are the issues that they are having and how are you resolving them? Would versioning have really helped? Or does your IDE require some tailoring that makes it out of sync?

**Comment by rei-vilo** [comment]
Latest review among embedXcode users shows only 1% uses Cosa. It is a pity because I thing Cosa deserves much more! 

Each time an issue is reported with Cosa, the first question is about the release dates and the comparison of each file of the framework line by line to spot the differences. 

Anyway, it was just a suggestion!

**Comment by mikaelpatel** [comment]
@rei-vilo 
I fully understand your concern but with only 1% usage among embedXcode users it see even more unmotivated to add the extra work. I have seen the same response on publishing updates on the Arduino forum. Cosa is regarded to be too difficult as an entry point for Arduino applications and experienced users seem to have found work-arounds for the short comings of the Arduino libraries and IDE.

I would really like to understand the type of problems that embedXcode users are having. And if this actually is helped by adding versioning. There must be more to the issues. Do you have any examples?

As I have understood it embedXcode does not add anything to the source code. There are no dependencies there so I am guessing it is mostly about configuration of tools. If it would be Cosa implementation issues I would hope that the users would be asked to file an issue here.

Anyway, I am thankful for your suggestions and will consider them in the refactoring work towards supporting ARM/SAM based boards.

**Comment by mikaelpatel** [comment]
@rei-vilo 
After a major refactoring of the Cosa core into a lean core and a large set of libraries it is high time for a tagged release. Please find it at https://github.com/mikaelpatel/Cosa/releases/tag/v1.0.0

Cheers!

**Comment by rei-vilo** [comment]
Thanks!
