### ISSUE TITLE
CosaWirelessDS18B20 with attiny85 unstable ?

### ISSUE THREAD

**Issue by mazkagaz** [mikaelpatel/Cosa#226]
Hello,

I tried yesterday your CosaWirelessDS18B20 arduino sketch and it worked like a charm (using virtualwire) : one message each 5 seconds, with two DS18B20.

I wanted to tune it for my personnal needs : only one DS18B20. There were no problem except I only received one message, the first one, and nothing else happened.

I thought the attiny did not wake up after deep sleep but I measured the DS18B20 input voltage (as the attiny feeds it when it is awaked) and I could observe this : 4.5v after switching on, message received on the other side (so everything OK), 0v (attiny sleeps), then 4.5v again (attiny woke up), and then, nothing else, 4.5v all the time without any other message send (nor received) and without any other sleep time for the attiny, as if it was in an infinite loop.

I tried to debug with a blinking led : depending on the place I put my debug output in the "loop" code, the code didn't stop at the same place.

I tried changing the attiny with another, reburn the bootloader, changing the emetter, changing the DS18B20: always the same.

I get back to the original sketch with two DS18B20, figuring I did something wrong and wanting to see it working again. The original sketch does the same: +4.5v, temperatures sended, 0v, +4.5v and then locked, nothing else happens.

May you have already had that issue and know what to do ? I wondered if there is an issue with watchdog that make the attiny freeze, because the led blinking debug make the sketch stop in a different state.

I'll go on looking for the problem and give you feed back if i find a/the solution.

Regards,

H. M.

**Comment by duayfabi** [comment]
Hi,

I exactly have the same problem with the latest version of the cosa library.

As client, I'm using the exemple sketch "CosaWirelessDS18B20" with the VirtualWire wireless driver.

As server, the "CosaWirelessReceiver" exemple sketch (with VirtualWire option).

I use the sketch "As is" (I only choose the VirtualWire wireless device driver). On my "Server", I only receive the first message and nothing else more.

I checked my hardware/shema. All seems to be good..

I can do a few check if you want. Let me know what to do..

Regards,

Fabien
