### ISSUE TITLE
Slow compile times ?

### ISSUE THREAD

**Issue by synergie7** [mikaelpatel/Cosa#240]
Hi,

I just downloaded and tried Cosa (for the first time), and the compile time for Cosa Blink is around 10 times slower than the normal Arduino Blink example.

Its taking 56 seconds to compile Cosa blink on a Core i5 machine (2.5gHz) (WIndows 7 64 bit) Arduino IDE 1.5.7

Is this normal for Cosa ?  As I think it would deter me from using Cosa, as the Arduino Blink only takes 5 seconds to compile

(Note, I'm only timing the compile / link etc not the upload)

PS. The board I'm using is a Duemilanove (I have not tested on other boards)

PS. CosaBenchmarkFSM.ino was a bit quicker to compile at 45 seconds, but still seems quiet slow

**Comment by mikaelpatel** [comment]
@synergie7 

The latest refactor (https://github.com/mikaelpatel/Cosa/releases) of Cosa introduces a much smaller set of core classes. The "extra" classes (drivers etc) are now in the libraries. This restructuring improves compile and build time for the Arduino IDE. The major drawback is that users must include from the libraries (with <>) and all dependent libraries must be included explicitly. Please see the example sketches in the libraries directory.
