### ISSUE TITLE
Where should GPS classes reside?

### ISSUE THREAD

**Issue by SlashDevin** [mikaelpatel/Cosa#254]
I am preparing to submit some GPS classes.  They including a base class and one derived class, although other derived classes may be contributed in the future.

IOStream/Driver seems likely, although those classes seem much more generic than an NMEA sentence parser.  Perhaps IOStream/Driver/GPS?

I just remembered... the ublox Neo-6M also has SPI, USB and i2C interfaces.  Maybe there should be a Cosa/GPS subdirectory?

Cheers,
Devin

**Comment by mikaelpatel** [comment]
@SlashDevin 

Yes, those are the basic library levels even if they would never become strict as this is an open-source project. The library and core directory structure is not locked down. It is fine to suggest changes. The current setup is more or less what came with adapting the Arduino core structure and keeping that is just to allow the Arduino IDE to be used. Right now there is a issue with the Arduino preprocessor for libraries as it does not understand other header extension than .h. 

"God fortsättning", Mikael
