### ISSUE TITLE
Enhance Watchdog/Periodic/Alarm/RTC/... for true millisecond resolution

### ISSUE THREAD

**Issue by jeditekunum** [mikaelpatel/Cosa#261]
These are all based on watchdog timer overflow and chip frequency which are all powers of 2.  The current implementation is an approximation of ms (unless a power of 2) and seconds units.  My PR https://github.com/mikaelpatel/Cosa/pull/250 was a temporary workaround for long-term (hours) accuracy of the RTC seconds clock at the expense of introducing jitter.

It is desirable for 1 ms to be exactly 1 ms (and therefore 1 second being exact as well).  It is desirable to be able to use intervals that are not a power of 2 (for example in Alarm).

Timer has the core parts required to do this.

I see this area has gone through a few iterations already so I'm inclined to leave the details to you.  I would be willing to work on it if you would be willing to converse about the direction you would like to pursue.  At the moment this is not stopping my projects as I'm using Timer to do what I need.

It would be worth including an interface to discipline the clock as well.

**Comment by mikaelpatel** [comment]
See commit https://github.com/mikaelpatel/Cosa/commit/2a52972ebe2295b4b2af74c1565c9f111e19499c.
