### ISSUE TITLE
ST7735 broken?

### ISSUE THREAD

**Issue by jediunix** [mikaelpatel/Cosa#291]
CosaCanvasFonts.ino is producing strange output.  Left 2/3 of screen is a mostly black sorta grid.  The right 1/3 has font characters overlaying each other.

Both my SPI & TWI OLED are working for the same font.

CosaCanvasDemo is broken too...

I see you just made some changes there so I will leave the debugging to you :)

**Comment by mikaelpatel** [comment]
The obvious question is if you are on the latest updates? I corrected that problem a few days ago.

**Comment by mikaelpatel** [comment]
You need to configure CosaCanvasFonts.ino for ST7735. The default is right now ILI9341. That will give a lot of problems run on a ST7735. See https://github.com/mikaelpatel/Cosa/blob/master/examples/Canvas/CosaCanvasFonts/CosaCanvasFonts.ino#L87

**Comment by mikaelpatel** [comment]
All Canvas example sketches are now back to default ST7735.

**Comment by jediunix** [comment]
Oops.  I didn't see that line.  I was thrown by the fact that I could see something :)

**Comment by mikaelpatel** [comment]
No problems. Actually this forced me to take a decision on which driver should be default. BW: Have you checked the performance of the new driver structure. Added some extra tricks and increased the SPI clock frequency.
