### ISSUE TITLE
Suggestion for "bits to bytes" macro in Types.h

### ISSUE THREAD

**Issue by jediunix** [mikaelpatel/Cosa#296]
While dealing with fonts an often occurring pattern was conversion of # of bits (/pixels) to # of bytes.

There is CHARBITS in Types.h.

Would be nice to have a macro to do this simple but tedious conversion.

Thanks

**Comment by mikaelpatel** [comment]
Something like:
#define BYTES(bits) (((bits) + (CHARBITS - 1)) / CHARBITS)
or maybe CHARS(bits). Naming is always difficult. 

Cheers!

**Comment by jediunix** [comment]
BYTES works better I think.  CHAR always has such loaded meaning...

**Comment by mikaelpatel** [comment]
Ok BYTES(bits) it is then. https://github.com/mikaelpatel/Cosa/commit/5ae81fd8958064d9ecfd90598609af46dbbe5747

**Comment by jediunix** [comment]
Thanks
