### ISSUE TITLE
SNMP MIB OIDs have a mangled root due to missing encoding

### ISSUE THREAD

**Issue by dansut** [mikaelpatel/Cosa#308]
The first byte of a ASN.1 BER encoded OID for SNMP should always be 0x2B as it has strangely compressed form of 1.3 => (40*1)+3 = 43 = 0x2B.

As is this is not done in the current Cosa SNMP implementation the effect is that of adding a 0. to the beginning of every OID and misplacing things in the 0.1.3.6.1 root as opposed to 1.3.6.1 where they really belong.

**Comment by mikaelpatel** [comment]
Updated the OIDs with the correct prefix. Have not test it on a board with W5100 yet. Please see commit https://github.com/mikaelpatel/Cosa/commit/c60eb1b56d0f4db0560f65fe7614bb43ee53f9e7.

**Comment by dansut** [comment]
Thanks for fix, I don't know why I didn't think to just do that.

Tested, and it works for snmpget on mib-2 stuff but CosaSNMP.ino example needs fixing for it to work with Arduino MIB - will give you a pull request on that.

However snmpwalk is broken by this change. I don't think it was ever supposed to work how documented in the example comment though ... leaving MIB off walk should start from 1.3.6.1.2.1 which is reasonable behavior.

**Comment by mikaelpatel** [comment]
Thanks for testing this. Much appreciated. I assumed there was going to be a few ripple effects on the examples, etc.

**Comment by dansut** [comment]
I think I have made snmpwalk again, and improved the example a little see pull request #313 
Cheers
