### ISSUE TITLE
Keep USB alive after an ASSERT failure

### ISSUE THREAD

**Issue by jeditekunum** [mikaelpatel/Cosa#343]
Failed ASSERT ends up calling `exit` via `trace.fatal`.  As I understand it, Arduino exit means disable interrupts and go into an infinite loop.  This prevents downloads without a reset button press.

When an ASSERT fails it should loop handling USB events so that the baud-shift-driven transfer to the bootloader still works.

Not sure of best way to implement this otherwise I would have PR.

**Comment by mikaelpatel** [comment]
One solution is to remove the exit() from fatal and just use a loop. This would work for when trace is included but the problem is the same when CDC is not used at all in ATmega32U4 based variants. 

I would also guess that there are still some timing issue when trying to reconnect to a CDC based device. It is difficult to do that gracefully.

**Comment by jeditekunum** [comment]
What do you think of this solution?  Obviously can't do anything about case where CDC isn't used.

https://github.com/jeditekunum/Cosa/commit/3b461d5ffb44f23743f52b2b7ae35d33906f247e

This seems to be completely reliable in my testing.  Interrupts are still disabled so no user code would run.  Takes care of any exit, not just assert.

With `ard-reset-arduino`, and recently `ard-wait-arduino`, watching for inode change I think most of the timing issues are gone.

**Comment by mikaelpatel** [comment]
I have test simple removing exit() from fatal and replacing it with an infinite loop. It seems to work fine as well. The behavior would be the same for all boards, e.g., the interrupt handlers are not disabled. There is only a print of the EXIT character followed by flush and the infinite loop.

**Comment by jeditekunum** [comment]
Opinions:
* bootloading should work whenever possible - including if the application has called `exit`
* `exit` should terminate the application; since the application could include interrupt handling I think that should be disabled

Implementing `exit` brings up another question... wouldn't it be desirable to print a string and then the EXIT character whenever `exit` was called?  Something like `**exited**`.

**Comment by jeditekunum** [comment]
Please see PR https://github.com/mikaelpatel/Cosa/pull/347

The message on exit needs to be deferred due to issue https://github.com/mikaelpatel/Cosa/issues/346
