### ISSUE TITLE
Vote: Add support for PJRC Teensy 3.1

### ISSUE THREAD

**Issue by mikaelpatel** [mikaelpatel/Cosa#361]
Towards issue https://github.com/mikaelpatel/Cosa/issues/349

**Comment by jeditekunum** [comment]
+1

**Comment by ladislas** [comment]
+1

**Comment by alexozer** [comment]
@ladislas: haven't I seen you before?
+1

**Comment by ladislas** [comment]
@alexozer yep, bare arduino project ;) looking forward to taking a look at your makefile and make output! :)

**Comment by alexozer** [comment]
@ladislas yep, it's embarrassing because I was getting everything ready for you but got distracted with this

**Comment by dansut** [comment]
+1
