### ISSUE TITLE
Vote: Add support for LPC8XX

### ISSUE THREAD

**Issue by mikaelpatel** [mikaelpatel/Cosa#371]
NCP/ARM Cortex-M0+ MCU. http://www.nxp.com/products/microcontrollers/product_series/lpc800/#overview

Possible starting ground for adding support for ARM.

**Comment by mikaelpatel** [comment]
Possible development board http://www.farnell.com/datasheets/1883897.pdf

**Comment by tht** [comment]
+1

Would love to see Cosa on these little devices... If you're looking for a development board I can recommend this one: http://www.aliexpress.com/item/ARM-CortexM0-LPC812-Development-Board-Minimum-System-Board-USB-to-Serial-ISP-Download/32234512606.html
Small, cheap, embedded RGB LED for some testing and the integrated USB-UART Bridge helps a lot as lpc21isp is easily able to upload to these boards without any additional hardware.

**Comment by jeditekunum** [comment]
+1 - maybe.

These would have limited value for me - only at the VERY lowest end. Good fit for AVR replacement. However, I wonder if the small size is going to be obsolete. When I can buy a Particle Photon with Cortex M3 + WiFi for $19...
