### ISSUE TITLE
NRF module initialization should fail in begin() if the module does not respond to our SPI commands

### ISSUE THREAD

**Issue by SinishaDjukic** [mikaelpatel/Cosa#372]
Please check out the patch here:
https://gist.github.com/SinishaDjukic/227b372ae06b2802a855

I've been struggling with some custom-built shields with flaky wiring and noticed that even if you don't connect the NRF module the begin asserts will pass and the rest of the sketch is executed.

**Comment by mikaelpatel** [comment]
Please see commit https://github.com/mikaelpatel/Cosa/commit/59d288f17e31f89b4ea824f7f8c4f62390788f67. Use status reserved bit (always zero).

**Comment by SinishaDjukic** [comment]
Looks good, thanks!
