### ISSUE TITLE
Allow RTC based Periodic actions

### ISSUE THREAD

**Issue by mikaelpatel** [mikaelpatel/Cosa#402]
Integrate Timer and Periodic to a single concept.

**Comment by kc9jud** [comment]
+1

**Comment by mikaelpatel** [comment]
First steps toward a common handler. See commit https://github.com/mikaelpatel/Cosa/commit/09ce0a9be1e756c2ebc76df6ea59dcae49d1a629.

**Comment by mikaelpatel** [comment]
Please see commit https://github.com/mikaelpatel/Cosa/commit/2a52972ebe2295b4b2af74c1565c9f111e19499c.
