### ISSUE TITLE
Soft::UART receive no longer working?

### ISSUE THREAD

**Issue by jeditekunum** [mikaelpatel/Cosa#425]
It seems this is no longer working. I am using latest source. CosaSoftUART only changed to different pins (D25 & PCI0 on Moteino Mega). I have tried several other PCI pins.

Test output is fine but it doesn't echo back any input. My larger app isn't seeing input either.

**Comment by mikaelpatel** [comment]
@jeditekunum 
Have you tried lower baudrates? I changed the PinChangeInterrupt implementation to save some SRAM. Tested on ATtiny. I will try it on ATmega and see.

**Comment by jeditekunum** [comment]
@mikaelpatel 

Yes, 9600. At first with GPS. Then tried example with FTDI.

**Comment by mikaelpatel** [comment]
@jeditekunum 
The CosaSoftUART example sketch works fine with Pro-Mini and the default setup D4(RX) and D5(TX) and 9600/57600 bps. I will have to test a few more configurations. Will get back with that.

**Comment by mikaelpatel** [comment]
@jeditekunum 
Did some more tests with Mega. Worked as it should. Found an issue with ATmega328 (Standard) based boards and PCI14 and up. The numbering was wrong when using analog pins for PCI. https://github.com/mikaelpatel/Cosa/commit/7e0033f9892c9426c3c502848bcd8f4c5238be9d. Also the Mega PCI pin definition needed some cleaning up as some of the pins where based on analog pin definitions which makes it extra difficult to read. https://github.com/mikaelpatel/Cosa/commit/10199c560216907eaa8bbf574f5838ab838eb1ce

I will have to take a look at the Moteino Mega board definition again.

**Comment by jeditekunum** [comment]
@mikaelpatel 

It is possible that this never worked with Moteino Mega as I never tested it when I did the board stuff :)

I hooked up my FTDI to uart1 to confirm that it is working. CosaMegaUARTs works fine.

I then moved to CosaSoftUART and moved my FTDI to the default pins. Nothing (not even output). Then changed baud rate to 9600; nothing. Changed to D0/D1(PCI9) and output worked but no input. Then changed to D1/D2(PCI10) and same thing.

Likely I did something wrong with the board stuff.

**Comment by mikaelpatel** [comment]
@jeditekunum 
I had a look at the pin mapping for PinChangeInterrupt. It is confusing and needs to be cleaned up. The mapping has to be the same as the corresponding pin as it is sub-classes from IOPin. But at the same time it has to be a mapping to the PCI interrupt and mask. I will look at this.

**Comment by jeditekunum** [comment]
@mikaelpatel 

Thanks. I used ATmega1284P.hh as the baseline so it will need cleanup too.

**Comment by mikaelpatel** [comment]
@jeditekunum 
Actually the ATmega1248P.hh should be just fine as it is a straight mapping with ports in natural order. It is not restricted to a physical layout as a board. I guess that the Microduino Core++ has the same issue. The new implementation with a list of handlers instead of a full table reveals any mapping errors as the lists are per port/mask register. The table version did not really care if the index was "correct" as long as the mapping was the same for register and indexing.

**Comment by mikaelpatel** [comment]
@jeditekunum 
There was several things to clean up in the PinChangeInterrupt code. Also the board definitions needed some work. When possible the PCIn are the same as the boards Dn. Special cases are MCU that have only a limited number of PCI-pins. Please see commit https://github.com/mikaelpatel/Cosa/commit/a13c5267fb90766b89706c88ebb2bdea82c2a28b.

**Comment by jeditekunum** [comment]
@mikaelpatel 

Works! Thanks!

**Comment by mikaelpatel** [comment]
@jeditekunum 
Thanks for the testing and feedback. The code was in need of a clean-up. Looked like I had left it in mid-air :). Must have got carried away with the UART optimization :)
