### ISSUE TITLE
Can't build any Cosa project : 

### ISSUE THREAD

**Issue by guiguid** [mikaelpatel/Cosa#446]
the sketch (hard to make simpler): 

void setup() {
}
void loop() {
}

/usr/share/arduino/hardware/tools/avr/bin/avr-gcc-ar rcs /tmp/build8822524449374858952.tmp/core.a /tmp/build8822524449374858952.tmp/AnalogComparator.cpp.o 

sorry - this program has been built without plugin support

GNU ar (GNU Binutils) 2.25.1
avr-gcc (GCC) 5.2.0
Linux manjaro 4.2.5-1-MANJARO
Arduino 1.6.5

ar is compiled with "enable-plugins" .... 

I don't understand ....

If I chose a "non Cosa card type", it works

**Comment by guiguid** [comment]
works perfectly with Cosa 1.0.3

**Comment by mikaelpatel** [comment]
Can you check what ar is used. https://github.com/mikaelpatel/Cosa/blob/master/platform.txt#L46

**Comment by mikaelpatel** [comment]
The answer was obvious if I checked the path of example. 

Try changing back to avr-ar.

**Comment by guiguid** [comment]
it works with : 
compiler.ar.cmd=avr-ar
it fails with 
compiler.ar.cmd=avr-gcc-ar

**Comment by mikaelpatel** [comment]
I guess this implies that we need to remove LTO support from the Arduino IDE build (again).
