### ISSUE TITLE
Driver: Add Socket implementation for ESP8266 (serial)

### ISSUE THREAD

**Issue by mikaelpatel** [mikaelpatel/Cosa#461]

**Comment by fortizpenaloza** [comment]
Hi, it's been a year since you created this issue and since Arduino is releasing an UNO with ESP8266 integrated i'd to ask: any plans to add it support to it?

See http://www.arduino.org/products/boards/arduino-uno-wifi

Thanks

**Comment by mikaelpatel** [comment]
@fortizpenaloza The Cosa issues list is very much out-of-date. This issue should have been queued a long time ago. Unfortunately I do not have any projects with ESP8266 and this has moved out of focus.
