### ISSUE TITLE
Always updatable libraries

### ISSUE THREAD

**Issue by per1234** [mikaelpatel/Cosa#476]
using Cosa 1.2.0(Boards Manager install) with Arduino IDE 1.6.7

- Select a Cosa board from Tools > Board
- Sketch > Include Library > Manage Libraries... > Type: Updatable

SD and Servo libraries appear as updatable but no matter what you do they can't be removed from the list(https://github.com/arduino/Arduino/issues/4189). This is caused because the name of the libraries(defaults to the folder name because no library.properties file is present) are the same as the SD and Servo libraries that are included with the Arduino IDE so this confuses Library Manager. The workaround I have found for this is to add a library.properties file to these libraries that has a unique name value, perhaps something like `SD(Cosa)`. This issue can also exacerbate the issue of https://github.com/arduino/Arduino/issues/4064 because it may cause the user to unnecessarily install these libraries to their sketchbook folder while attempting to "update" which will then override the version of the library included with Cosa. The unique name value workaround will not solve the override issue but will only prevent libraries from falsely being listed as updatable. This issue will also occur with IDE versions previous to 1.6.7. The SD library can be successfully removed from the Updatable list in the hourly build of Arduino IDE but only because the version of that library included with the hourly build(1.0.7) is higher than the latest version available via Library Manager(1.0.6) so "updating" will actually install 1.0.6 to the sketchbook/libraries folder.

There is also a related issue with the PCD8544 library. Library Manager will show this library to be updatable, although it doesn't have the always updatable issue because it's not included with the Arduino IDE, doing the update will install the non-Cosa version of that library to be installed to the sketchbook/libraries folder where it will cause the override issue. Adding a library.properties file with a unique name value to this library will prevent it from falsely showing as updatable.

**Comment by mikaelpatel** [comment]
I can only acknowledge and agree. There is a lot of library handling that needs cleaning up to avoid all the warnings from the Arduino IDE Library Manager. The conflicts are maybe the more severe issue.

In any case, please find an update that at least for now removes some of these. 

Thanks for providing all this info!
