### ISSUE TITLE
Advice: Using rotary encoder connected to I/O expander

### ISSUE THREAD

**Issue by nitinsane** [mikaelpatel/Cosa#482]
I have a rotary encoder connected to the two digital pins of an I/O expander. Is there any way to use Cosa code to support this? I do see the DigitalPin abstraction but the IO Expander classes do not use it. Any ideas?

**Comment by mikaelpatel** [comment]
What type of I/O expander? If you are thinking about using an I2C variant I think that the possible interrupt/sample rate is much too slow.

**Comment by nitinsane** [comment]
I am planning to use MCP23017/8. I have not yet done any experimentation to see what kind of response I get.

**Comment by kc9jud** [comment]
I might suggest using the a chip dedicated to reading out rotary encoders -- I've used http://www.lsicsi.com/counters.htm before and been very happy. I have a Cosa-compatible library I wrote for the LS7366R that I could clean up and contribute if anyone has a use for it.

**Comment by nitinsane** [comment]
That's an interesting idea. Please share the code if you can.
Thanks.

On Tue, Mar 22, 2016 at 8:33 PM, Patrick Fasano <notifications@github.com>
wrote:

> I might suggest using the a chip dedicated to reading out rotary encoders
> -- I've used http://www.lsicsi.com/counters.htm before and been very
> happy. I have a Cosa-compatible library I wrote for the LS7366R that I
> could clean up and contribute if anyone has a use for it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mikaelpatel/Cosa/issues/482#issuecomment-200093740>
>



-- 
*Nitin Sane*
nitinsane@gmail.com
