### ISSUE TITLE
API Documentation link is stale...

### ISSUE THREAD

**Issue by WestfW** [mikaelpatel/Cosa#496]
The link in the readme file refers to a non-existent file...
http://dl.dropbox.com/u/993383/Cosa/doc/html/index.html

**Comment by mikaelpatel** [comment]
Seems like dropbox has changed their policy for handling public folders. Need to rethink how to store on-line documentation.

**Comment by WestfW** [comment]
I noticed recently that github displays markdown and acts on links therein for files in a repository (not just in their "wiki" sections.)   So if you're not getting complicated with your html, that might be an alternative.  I don't know how hard the conversion would be.

**Comment by gregori** [comment]
Is it possible to provide the documentation somewhere else for download?
As for publishing online, what about using github pages?

**Comment by mikaelpatel** [comment]
@WestfW @gregori 
Time to clean up this mess. Sorry for the delay. 
https://mikaelpatel.github.io/Cosa/index.html
The documentation zip may be found in the release handling on github. 
https://github.com/mikaelpatel/Cosa/releases
