### ISSUE TITLE
please provide examples of async analog read handling

### ISSUE THREAD

**Issue by dothebart** [mikaelpatel/Cosa#508]
One of the proclaimed advantages of cosa above the genuine arduino library is to provide programming models to keep the yC operational while analog values are read. While there are many excelent examples howto achieve simple tasks with cosa, examples howto achieve async reads with the current cosa are missing. 
Please provide simple examples, that 

1)
 - uses a timer to trigger frequent analog reads on intervals
 - has a callback handler that is invoked once the analog read is finished, and decides on a threshhold whether it should turn on/off a LED via a digital port

2)
 - have a TWI slave that receives a command
 - triggers an analog read 
 - once the read is done return the analog value via TWI

In both cases please demonstrate the pseudo parallelism by blinking a second led via a second digital port.

**Comment by mikaelpatel** [comment]
Nice suggestions :) Please feel free to add these examples. Examples of asynchronous handling of AnalogPin can be found in the Benchmark directory; https://github.com/mikaelpatel/Cosa/blob/master/examples/Benchmarks/CosaBenchmarkDataLogger/CosaBenchmarkDataLogger.ino#L113, and in the Sandbox, https://github.com/mikaelpatel/Cosa/blob/master/examples/Sandbox/CosaVCC/CosaVCC.ino#L71, also the Keypad is implemented with Event Handler, https://github.com/mikaelpatel/Cosa/blob/master/cores/cosa/Cosa/Keypad.cpp#L24.
