### ISSUE TITLE
Hamming codec for cheap radios question

### ISSUE THREAD

**Issue by barbiani** [mikaelpatel/Cosa#513]
Is the codec alone enough to drive an OOK radio or the manchester also needs to be in the codec cascade?

**Comment by mikaelpatel** [comment]
The VWI::Codec is a pure virtual class. https://github.com/mikaelpatel/Cosa/blob/3a6a9ffe538539374efae35dab83303e0e14dad0/libraries/VWI/VWI.hh#L73

An implementation VWI::Codec is required. VirtualWireCodec is the original https://github.com/mikaelpatel/Cosa/tree/master/libraries/VirtualWireCodec. There is also two other Hamming Codec bases codecs. And a Manchester Codec.
