### ISSUE TITLE
Is this platform still viable ?

### ISSUE THREAD

**Issue by umbr1X** [mikaelpatel/Cosa#514]
Does it encounter any bugs ? I can see that it clearly wins by overfeatures against the Arduino platform but is it stable? Because otherwise that will be a huge loss

**Comment by mikaelpatel** [comment]
@xshadowbringer 
I am sorry to say that there has not been much work done on Cosa the latest five years. Some experimentation has been done to allow easier port to other MCUs and more component based implementation approach. These libraries can be found in here.
